In [30]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score,confusion_matrix,classification_report
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [19]:
def scores(y_test,prediction):
#     print("Accuracy: " + str(accuracy_score(y_test, prediction) * 100) + "%")
#     print("Precision: " + str(precision_score(y_test, prediction) * 100) + "%")
#     print("F1 score: " + str(f1_score(y_test, prediction) * 100) + "%")
#     print("Recall: " + str(recall_score(y_test, prediction) * 100) + "%")
#    scores = []
#    scores.append(accuracy_score(y_test, prediction) * 100)
#    scores.append(precision_score(y_test, prediction) * 100)
#    scores.append(f1_score(y_test, prediction) * 100)
#    scores.append(recall_score(y_test, prediction) * 100) 
    print(confusion_matrix(y_test,prediction))
    print(classification_report(y_test, prediction, target_names=["red wine","white wine"]))
#    return scores

In [8]:
#carregando dataset de vinhos brancos e vermelhos
wines = pd.read_csv('wines.csv',sep=",")
#separando dados e saidas
X = wines.iloc[:,0:12]
Y = wines.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.20, random_state=42)

In [12]:
# Create a random forest Classifier. By convention, clf means 'Classifier'
clf = RandomForestClassifier(n_jobs=10, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (the species)
clf.fit(X_train, y_train)

C:\Users\Paulo Alencar\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=10,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [13]:
prediction = clf.predict(X_test)

In [14]:
scores(y_test,prediction)

              precision    recall  f1-score   support

    red wine       0.99      0.98      0.98       333
  white wine       0.99      1.00      0.99       967

   micro avg       0.99      0.99      0.99      1300
   macro avg       0.99      0.99      0.99      1300
weighted avg       0.99      0.99      0.99      1300



[99.15384615384616, 99.1769547325103, 99.43269726663229, 99.68976215098242]

In [31]:
normalizer = Normalizer(norm='l1')
winesl1 = X.copy()
winesl1.iloc[0:,0:12] = normalizer.transform(X)
winesl1.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.030496          0.000659     0.001236        0.056459   0.000231   
1       0.037031          0.002051     0.001766        0.077195   0.000302   
2       0.086411          0.003227     0.004060        0.024986   0.000812   
3       0.036697          0.003556     0.002356        0.009061   0.000553   
4       0.042753          0.001579     0.002499        0.006577   0.000178   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.135996              0.692343  0.004114  0.011951   0.001813   
1             0.113942              0.643770  0.005671  0.018231   0.003190   
2             0.176987              0.447672  0.010353  0.034460   0.008016   
3             0.167630              0.693174  0.004517  0.014543   0.003126   
4             0.203899              0.591964  0.006507  0.021311   0.002368   

    alcohol   quality  
0  0.035853  0.028848  
1  0.062668  0.034182  
2  0.130137  0.072877  
3  0.042134  0.022653  
4  0.080902  0.039464

<h2> Função Kfold </h2>

In [17]:
def cross_validation(dados,folds=10):
    kf = KFold(n_splits=folds)
    for train_index, test_index in kf.split(dados):
        X_train, X_test = dados.iloc[train_index], dados.iloc[test_index]
        y_train, y_test = Y[train_index], Y[test_index]
        model = clf.fit(X_train,y_train)
        prediction = model.predict(X_test)
        print(scores(y_test,prediction))

In [20]:
cross_validation(winesl1)

[[156   4]
 [  1 489]]
              precision    recall  f1-score   support

    red wine       0.99      0.97      0.98       160
  white wine       0.99      1.00      0.99       490

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[153   1]
 [  3 493]]
              precision    recall  f1-score   support

    red wine       0.98      0.99      0.99       154
  white wine       1.00      0.99      1.00       496

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[164   5]
 [  3 478]]
              precision    recall  f1-score   support

    red wine       0.98      0.97      0.98       169
  white wine       0.99      0.99      0.99       481

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.98      0.98      

In [21]:
normalizer = Normalizer(norm='l2')
winesl2 = X.copy()
winesl2.iloc[0:,0:12] = normalizer.transform(X)
winesl2.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.042946          0.000929     0.001741        0.079509   0.000325   
1       0.055812          0.003091     0.002662        0.116346   0.000455   
2       0.168350          0.006288     0.007910        0.048680   0.001582   
3       0.051258          0.004968     0.003291        0.012656   0.000772   
4       0.067390          0.002488     0.003940        0.010368   0.000280   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.191518              0.975001  0.005793  0.016830   0.002554   
1             0.171728              0.970265  0.008547  0.027477   0.004808   
2             0.344813              0.872175  0.020170  0.067137   0.015618   
3             0.234141              0.968204  0.006309  0.020313   0.004366   
4             0.321397              0.933089  0.010256  0.033591   0.003732   

    alcohol   quality  
0  0.050491  0.040625  
1  0.094451  0.051519  
2  0.253539  0.141982  
3  0.058852  0.031641  
4  0.127522  0.062206

In [23]:
cross_validation(winesl2)

[[156   4]
 [  5 485]]
              precision    recall  f1-score   support

    red wine       0.97      0.97      0.97       160
  white wine       0.99      0.99      0.99       490

   micro avg       0.99      0.99      0.99       650
   macro avg       0.98      0.98      0.98       650
weighted avg       0.99      0.99      0.99       650

None
[[152   2]
 [  3 493]]
              precision    recall  f1-score   support

    red wine       0.98      0.99      0.98       154
  white wine       1.00      0.99      0.99       496

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[163   6]
 [  3 478]]
              precision    recall  f1-score   support

    red wine       0.98      0.96      0.97       169
  white wine       0.99      0.99      0.99       481

   micro avg       0.99      0.99      0.99       650
   macro avg       0.98      0.98      0.98      

In [24]:
normalizer = Normalizer(norm='max')
winesmax = X.copy()
winesmax.iloc[0:,0:12] = normalizer.transform(X)
winesmax.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       0.044048          0.000952     0.001786        0.081548   0.000333   
1       0.057522          0.003186     0.002743        0.119912   0.000469   
2       0.193023          0.007209     0.009070        0.055814   0.001814   
3       0.052941          0.005131     0.003399        0.013072   0.000797   
4       0.072222          0.002667     0.004222        0.011111   0.000300   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             0.196429                   1.0  0.005942  0.017262   0.002619   
1             0.176991                   1.0  0.008809  0.028319   0.004956   
2             0.395349                   1.0  0.023127  0.076977   0.017907   
3             0.241830                   1.0  0.006516  0.020980   0.004510   
4             0.344444                   1.0  0.010992  0.036000   0.004000   

    alcohol   quality  
0  0.051786  0.041667  
1  0.097345  0.053097  
2  0.290698  0.162791  
3  0.060784  0.032680  
4  0.136667  0.066667

In [25]:
cross_validation(winesmax)

[[156   4]
 [  1 489]]
              precision    recall  f1-score   support

    red wine       0.99      0.97      0.98       160
  white wine       0.99      1.00      0.99       490

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[152   2]
 [  4 492]]
              precision    recall  f1-score   support

    red wine       0.97      0.99      0.98       154
  white wine       1.00      0.99      0.99       496

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[164   5]
 [  2 479]]
              precision    recall  f1-score   support

    red wine       0.99      0.97      0.98       169
  white wine       0.99      1.00      0.99       481

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.98      0.99      

In [26]:
scaller = MinMaxScaler(feature_range=(0, 12))
winesminmax = X.copy()
winesminmax.iloc[0:,0:12] = scaller.fit_transform(X)
winesminmax.head()

C:\Users\Paulo Alencar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       3.570248              0.64     2.168675        2.411043   0.936877   
1       2.677686              2.24     2.240964        2.383436   0.877076   
2       4.462810              1.84     2.819277        0.331288   1.375415   
3       4.264463              5.64     3.759036        0.257669   2.252492   
4       2.677686              1.28     2.746988        0.073620   0.358804   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0             1.333333              4.479263  2.577212  1.674419   1.483146   
1             0.791667              2.958525  1.927126  4.465116   2.292135   
2             0.666667              1.023041  1.695778  5.488372   3.707865   
3             1.500000              4.064516  2.264893  4.558140   3.168539   
4             1.250000              2.322581  0.497397  4.837209   0.943820   

    alcohol  quality  
0  1.217391      8.0  
1  5.217391      6.0  
2  7.826087      8.0  
3  2.260870      4.0  
4  7.478261      6.0

In [27]:
cross_validation(winesminmax)

[[157   3]
 [  0 490]]
              precision    recall  f1-score   support

    red wine       1.00      0.98      0.99       160
  white wine       0.99      1.00      1.00       490

   micro avg       1.00      1.00      1.00       650
   macro avg       1.00      0.99      0.99       650
weighted avg       1.00      1.00      1.00       650

None
[[152   2]
 [  1 495]]
              precision    recall  f1-score   support

    red wine       0.99      0.99      0.99       154
  white wine       1.00      1.00      1.00       496

   micro avg       1.00      1.00      1.00       650
   macro avg       0.99      0.99      0.99       650
weighted avg       1.00      1.00      1.00       650

None
[[166   3]
 [  2 479]]
              precision    recall  f1-score   support

    red wine       0.99      0.98      0.99       169
  white wine       0.99      1.00      0.99       481

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99      

In [32]:
# Create scaler
scaler = preprocessing.StandardScaler()

# Transform the feature
standardized = scaler.fit_transform(X)

# Show feature
winesS = X.copy()
winesS.iloc[0:,0:12] = standardized

C:\Users\Paulo Alencar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Paulo Alencar\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [33]:
cross_validation(winesS)

[[157   3]
 [  0 490]]
              precision    recall  f1-score   support

    red wine       1.00      0.98      0.99       160
  white wine       0.99      1.00      1.00       490

   micro avg       1.00      1.00      1.00       650
   macro avg       1.00      0.99      0.99       650
weighted avg       1.00      1.00      1.00       650

None
[[151   3]
 [  1 495]]
              precision    recall  f1-score   support

    red wine       0.99      0.98      0.99       154
  white wine       0.99      1.00      1.00       496

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99       650
weighted avg       0.99      0.99      0.99       650

None
[[166   3]
 [  2 479]]
              precision    recall  f1-score   support

    red wine       0.99      0.98      0.99       169
  white wine       0.99      1.00      0.99       481

   micro avg       0.99      0.99      0.99       650
   macro avg       0.99      0.99      0.99      